server:
  port: 8085
  benchmark:
    sleep-time: 13000
  tomcat:
    keep-alive-timeout: 20000
    max-keep-alive-requests: 10000
    max-connections: 30000
    max-threads: 200  
management:
  endpoints:
    web:
      exposure:
        include: health,info,beans,conditions,prometheus
        exclude: threaddump, heapdump
    prometheus: 
      enabled: true