apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: maven-source-pvc
  namespace: sa-benchmark
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  volumeMode: Filesystem