apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: tekton-pipeline
  namespace: sa-benchmark
spec:
  workspaces:
    - name: pipeline-shared-data
  params:
    - name: image-repo
      type: string
      description: Docker image name
      default: 192.168.173.38:5001/superapp-spring-benchmark  
  tasks:
    - name: clone-repository
      params:
        - name: url
          value: https://github.com/tmax-cloud/superapp-spring-benchmark.git
        - name: revision
          value: "main"
        - name: deleteExisting
          value: "true"
      taskRef:
        kind: Task
        name: git-clone
      workspaces:
        - name: output
          workspace: pipeline-shared-data
    - name: build-image
      runAfter:
        - clone-repository
      params:
        - name: IMAGE
          value: "$(params.image-repo):$(tasks.clone-repository.results.commit)"
      taskRef:
        kind: Task
        name: buildah
      workspaces:
        - name: source
          workspace: pipeline-shared-data
